export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const ORDERS_DETAILS_REQUEST = "ORDERS_DETAILS_REQUEST";
export const ORDERS_DETAILS_SUCCESS = "ORDERS_DETAILS_SUCCESS";
export const ORDERS_DETAILS_FAIL = "ORDERS_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
